version: "3"

services:

  lusid-sdk-csharp-gen:
    container_name: lusid-sdk-csharp-gen
    build: .
    image: finbourne/lusid-sdk-csharp-gen
    volumes:
      - .:/usr/swagger
    command: /usr/swagger/generate.sh lusid.json